Repository Cyggnus/ShuffleGenie, pull requests merged in 2023-08, with the labels that each got.

#20 [1.1.0] - Hotfix wrong manifest link
  index.html
  src/index.css
Labels: bug

#25 [1.2.5] - Add support for multiple languages
  README.md
  README_PT-BR.md
  SECURITY.md
  package-lock.json
  package.json
  src/Components/LanguageButton/index.tsx
  src/Components/LanguageModal/index.tsx
  src/Interfaces/LanguageButtonIProps.ts
  src/data/supportedLangList.ts
  src/i18n.ts
  src/i18n/locales/de/german.json
  src/i18n/locales/en/english.json
  src/i18n/locales/es/spanish.json
  src/i18n/locales/fr/french.json
  src/i18n/locales/hi/hindi.json
  src/i18n/locales/it/italian.json
  src/i18n/locales/ja/japanese.json
  src/i18n/locales/ko/korean.json
  src/i18n/locales/nl/dutch.json
  src/i18n/locales/pt_BR/brazilian.json
  src/i18n/locales/ru/russian.json
  src/i18n/locales/uk/ukrainian.json
  src/i18n/locales/zh/chinese.json
Labels: new version

#26 [1.3.0] - Add responsive style to hamburgerMenu and LanguageModal
  README.md
  README_PT-BR.md
  SECURITY.md
  package-lock.json
  package.json
  src/Components/LanguageModal/index.tsx
  src/Components/NavBar/NavDesktop/index.tsx
  src/Components/NavBar/NavMobile/index.tsx
  src/index.css
Labels: style, new version

#28 [1.3.0] - Hotfix format username correctly
  src/Components/SyncForm/index.tsx
Labels: bug
